(function(){'use strict';
  const NS='http://www.w3.org/2000/svg',colors=['#ff5d73','#4dabf7','#ffd166','#50d890','#b784f7'],symbols=['●','▲','■','◆','★'];
  const $=s=>document.querySelector(s),svg=(tag,attrs={})=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e};
  let progress=OrbitStorage.load(),level,state,initial,history=[],moves=0,busy=false,cleared=false,renderAngles=[],audio;
  function show(name){['game','level','settings'].forEach(n=>$(`#${n}Screen`).classList.toggle('hidden',n!==name));$('#clearDialog').classList.add('hidden')}
  function loadLevel(id){level=COLOR_ORBIT_LEVELS[id-1];initial=level.initial.slice();state=initial.slice();renderAngles=state.map(v=>v*360/level.slots);history=[];moves=0;busy=false;cleared=false;show('game');buildBoard();updateUI()}
  function polar(r,a){const q=(a-90)*Math.PI/180;return[180+r*Math.cos(q),180+r*Math.sin(q)]}
  function buildBoard(){const board=$('#board');board.textContent='';const gap=level.rings===5?27:32,outer=154,radii=Array.from({length:level.rings},(_,i)=>outer-i*gap);
    radii.forEach((r,i)=>{board.append(svg('circle',{cx:180,cy:180,r,class:'ring-track','stroke-width':gap-7}));const group=svg('g',{class:'ring-group','data-ring':i});for(let s=0;s<level.slots;s++){const [x,y]=polar(r,s*360/level.slots),g=svg('g');g.append(svg('circle',{cx:x,cy:y,r:level.rings===5?11:13,fill:colors[s],class:'tile tile-halo'}));if(progress.settings.colorHelp){const t=svg('text',{x,y:y+1,class:'tile-symbol'});t.textContent=symbols[s];g.append(t)}group.append(g)}board.append(group);board.append(svg('circle',{cx:180,cy:180,r,'stroke-width':gap,class:'ring-hit','data-hit':i}));
      const effects=level.effects[i].map((v,j)=>v&&j!==i?`${j+1}${v>0?'↻':'↺'}`:'').filter(Boolean);if(effects.length){const [x,y]=polar(r,90);const m=svg('text',{x,y:y+3,class:'link-mark'});m.textContent=effects.join(' ');board.append(m)}});
    board.append(svg('circle',{cx:180,cy:180,r:level.rings===5?27:38,class:'center-core'}));const t=svg('text',{x:180,y:183,class:'center-label'});t.textContent='ORBIT';board.append(t);render();bindBoard()}
  function render(){document.querySelectorAll('.ring-group').forEach((g,i)=>g.style.transform=`rotate(${renderAngles[i]}deg)`)}
  function updateUI(){$('#levelLabel').textContent=`LEVEL ${level.id}`;$('#moveCount').textContent=moves;$('#bestMoves').textContent=progress.bestMoves[level.id]??'—';$('#levelHint').textContent=level.hint;$('#undoButton').disabled=!history.length||busy;$('#resetButton').disabled=busy}
  function rotate(source,direction,{undo=false}={}){if(busy||cleared)return;busy=true;history.push({state:state.slice(),angles:renderAngles.slice()});state=OrbitSolver.apply(state,level.effects,source,direction,level.slots);level.effects[source].forEach((effect,i)=>renderAngles[i]+=effect*direction*360/level.slots);if(!undo)moves++;render();sound(220,.045);updateUI();setTimeout(()=>{busy=false;updateUI();if(OrbitSolver.solved(state))finish()},250)}
  function undo(){if(busy||!history.length||cleared)return;const prev=history.pop();state=prev.state;renderAngles=prev.angles;moves=Math.max(0,moves-1);render();sound(160,.04);updateUI()}
  function reset(){if(busy)return;state=initial.slice();renderAngles=state.map(v=>v*360/level.slots);history=[];moves=0;cleared=false;render();updateUI()}
  function finish(){cleared=true;const optimum=OrbitSolver.solve(level).moves,stars=moves<=optimum+1?3:moves<=optimum+4?2:1;OrbitStorage.recordClear(progress,level.id,moves,stars);$('#clearPulse').classList.add('show');sound(440,.1);setTimeout(()=>sound(660,.16),100);setTimeout(()=>{ $('#clearPulse').classList.remove('show');$('#stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('#clearStats').textContent=`${moves} MOVES · BEST ${optimum}`;$('#nextButton').classList.toggle('hidden',level.id===20);$('#clearDialog').classList.remove('hidden')},650)}
  function bindBoard(){let touch=null;document.querySelectorAll('.ring-hit').forEach(hit=>{hit.addEventListener('pointerdown',e=>{if(busy)return;const ring=+hit.dataset.hit;touch={ring,x:e.clientX};hit.setPointerCapture(e.pointerId);document.querySelector(`.ring-group[data-ring="${ring}"]`).classList.add('active')});hit.addEventListener('pointerup',e=>{if(!touch)return;const {ring,x}=touch,dx=e.clientX-x;document.querySelector(`.ring-group[data-ring="${ring}"]`).classList.remove('active');touch=null;const rect=$('#board').getBoundingClientRect(),dir=Math.abs(dx)>24?(dx>0?1:-1):(e.clientX<rect.left+rect.width/2?-1:1);rotate(ring,dir)});hit.addEventListener('pointercancel',()=>{document.querySelectorAll('.ring-group').forEach(g=>g.classList.remove('active'));touch=null})})}
  function sound(freq,duration){if(!progress.settings.sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch(_){}}
  function levelSelect(){const grid=$('#levelGrid');grid.textContent='';COLOR_ORBIT_LEVELS.forEach(l=>{const b=document.createElement('button'),open=l.id<=progress.unlocked;b.className='level-card'+(open?'':' locked');b.disabled=!open;b.innerHTML=`${l.id}<small>${'★'.repeat(progress.stars[l.id]||0)}</small>`;b.onclick=()=>loadLevel(l.id);grid.append(b)});show('level')}
  $('#undoButton').onclick=undo;$('#resetButton').onclick=reset;$('#levelsButton').onclick=levelSelect;$('#settingsButton').onclick=()=>{show('settings');$('#soundToggle').checked=progress.settings.sound;$('#colorHelpToggle').checked=progress.settings.colorHelp};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>show('game'));$('#soundToggle').onchange=e=>{progress.settings.sound=e.target.checked;OrbitStorage.save(progress)};$('#colorHelpToggle').onchange=e=>{progress.settings.colorHelp=e.target.checked;OrbitStorage.save(progress);buildBoard()};$('#nextButton').onclick=()=>loadLevel(level.id+1);$('#retryButton').onclick=()=>loadLevel(level.id);$('#selectButton').onclick=levelSelect;
  loadLevel(Math.min(progress.unlocked,20));
})();
