(function(){'use strict';
  const NS='http://www.w3.org/2000/svg',palette={R:'#ff5d73',B:'#4dabf7',Y:'#ffd166',G:'#50d890'},classicColors=Object.values(palette).concat('#b784f7'),symbols={R:'●',B:'▲',Y:'■',G:'◆'};
  const $=s=>document.querySelector(s),svg=(tag,attrs={})=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e};
  let progress=OrbitStorage.load(),mode='classic',level,state,initial,history=[],moves=0,busy=false,cleared=false,renderAngles=[],audio,selectMode='classic';
  const copy=s=>mode==='gate'?s.map(r=>r.slice()):s.slice();
  function show(name){['game','level','settings'].forEach(n=>$(`#${n}Screen`).classList.toggle('hidden',n!==name));$('#clearDialog').classList.add('hidden')}
  function loadLevel(id,nextMode=mode){mode=nextMode;level=(mode==='gate'?COLOR_ORBIT_GATE_LEVELS:COLOR_ORBIT_LEVELS)[id-1];initial=mode==='gate'?level.rings.map(r=>r.slice()):level.initial.slice();state=copy(initial);renderAngles=mode==='gate'?[0,0,0]:state.map(v=>v*360/level.slots);history=[];moves=0;busy=false;cleared=false;show('game');buildBoard();updateUI()}
  function polar(r,a){const q=(a-90)*Math.PI/180;return[180+r*Math.cos(q),180+r*Math.sin(q)]}
  function tile(group,x,y,color,key){const g=svg('g');g.append(svg('circle',{cx:x,cy:y,r:13,fill:color,class:'tile tile-halo'}));if(progress.settings.colorHelp){const t=svg('text',{x,y:y+1,class:'tile-symbol'});t.textContent=key?symbols[key]:'';g.append(t)}group.append(g)}
  function buildBoard(){const board=$('#board');board.textContent='';if(mode==='gate')buildGateBoard(board);else buildClassicBoard(board);bindBoard()}
  function buildClassicBoard(board){const gap=level.rings===5?27:32,outer=154,radii=Array.from({length:level.rings},(_,i)=>outer-i*gap);radii.forEach((r,i)=>{board.append(svg('circle',{cx:180,cy:180,r,class:'ring-track','stroke-width':gap-7}));const group=svg('g',{class:'ring-group','data-ring':i});for(let s=0;s<level.slots;s++){const [x,y]=polar(r,s*360/level.slots);tile(group,x,y,classicColors[s])}board.append(group);board.append(svg('circle',{cx:180,cy:180,r,'stroke-width':gap,class:'ring-hit','data-hit':i}));const effects=level.effects[i].map((v,j)=>v&&j!==i?`${j+1}${v>0?'↻':'↺'}`:'').filter(Boolean);if(effects.length){const [x,y]=polar(r,90),m=svg('text',{x,y:y+3,class:'link-mark'});m.textContent=effects.join(' ');board.append(m)}});addCore(board);render()}
  function buildGateBoard(board){const radii=[146,104,62];radii.forEach((r,i)=>{board.append(svg('circle',{cx:180,cy:180,r,class:'ring-track','stroke-width':28}));const group=svg('g',{class:'ring-group','data-ring':i});state[i].forEach((key,s)=>{const [x,y]=polar(r,s*90);tile(group,x,y,palette[key],key)});board.append(group);board.append(svg('circle',{cx:180,cy:180,r,'stroke-width':31,class:'ring-hit','data-hit':i}))});addCore(board);[0,1].forEach(gate=>{const x=180+(gate===0?125:83),button=svg('g',{class:'gate-button','data-gate':gate,role:'button','aria-label':`GATE ${gate?'B':'A'} 色を交換`,tabindex:0});button.append(svg('circle',{cx:x,cy:180,r:22,class:'gate-hit'}));const t=svg('text',{x,y:184,class:'gate-label'});t.textContent='⇄';button.append(t);board.append(button)})}
  function addCore(board){board.append(svg('circle',{cx:180,cy:180,r:mode==='gate'?27:level.rings===5?27:38,class:'center-core'}));const t=svg('text',{x:180,y:183,class:'center-label'});t.textContent=mode==='gate'?'GATE':'ORBIT';board.append(t)}
  function render(){document.querySelectorAll('.ring-group').forEach((g,i)=>g.style.transform=`rotate(${renderAngles[i]}deg)`)}
  function updateUI(){const data=mode==='gate'?progress.gate:progress;$('#levelLabel').textContent=mode==='gate'?`GATE TEST ${level.id}`:`LEVEL ${level.id}`;$('#moveCount').textContent=moves;$('#bestMoves').textContent=data.bestMoves[level.id]??'—';$('#levelHint').textContent=level.hint;$('#undoButton').disabled=!history.length||busy;$('#resetButton').disabled=busy}
  function remember(){history.push({state:copy(state),angles:renderAngles.slice()});moves++}
  function rotate(source,direction){if(busy||cleared)return;busy=true;remember();if(mode==='gate'){state=OrbitSolver.applyGate(state,{type:'rotate',ring:source,direction});renderAngles[source]+=direction*90}else{state=OrbitSolver.apply(state,level.effects,source,direction,level.slots);level.effects[source].forEach((effect,i)=>renderAngles[i]+=effect*direction*360/level.slots)}render();sound(220,.045);updateUI();setTimeout(()=>{busy=false;if(mode==='gate'){renderAngles=[0,0,0];buildBoard()}updateUI();checkClear()},250)}
  function swap(gate){if(mode!=='gate'||busy||cleared)return;remember();state=OrbitSolver.applyGate(state,{type:'swap',gate});buildBoard();const button=document.querySelector(`[data-gate="${gate}"]`);button.classList.add('swapped');busy=true;sound(330,.06);updateUI();setTimeout(()=>{busy=false;button.classList.remove('swapped');updateUI();checkClear()},240)}
  function undo(){if(busy||!history.length||cleared)return;const prev=history.pop();state=prev.state;renderAngles=prev.angles;moves=Math.max(0,moves-1);buildBoard();sound(160,.04);updateUI()}
  function reset(){if(busy)return;state=copy(initial);renderAngles=mode==='gate'?[0,0,0]:state.map(v=>v*360/level.slots);history=[];moves=0;cleared=false;buildBoard();updateUI()}
  function checkClear(){if(mode==='gate'?OrbitSolver.gateSolved(state):OrbitSolver.solved(state))finish()}
  function finish(){cleared=true;const optimum=(mode==='gate'?OrbitSolver.solveGate(level):OrbitSolver.solve(level)).moves,stars=moves<=optimum+1?3:moves<=optimum+4?2:1;if(mode==='gate')OrbitStorage.recordGateClear(progress,level.id,moves,stars);else OrbitStorage.recordClear(progress,level.id,moves,stars);$('#clearPulse').classList.add('show');sound(440,.1);setTimeout(()=>sound(660,.16),100);setTimeout(()=>{$('#clearPulse').classList.remove('show');$('#stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('#clearStats').textContent=`${moves} MOVES · OPTIMUM ${optimum}`;$('#nextButton').classList.toggle('hidden',level.id===(mode==='gate'?5:20));$('#clearDialog').classList.remove('hidden')},650)}
  function bindBoard(){let touch=null;document.querySelectorAll('.ring-hit').forEach(hit=>{hit.addEventListener('pointerdown',e=>{if(busy)return;const ring=+hit.dataset.hit;touch={ring,x:e.clientX};hit.setPointerCapture(e.pointerId);document.querySelector(`.ring-group[data-ring="${ring}"]`).classList.add('active')});hit.addEventListener('pointerup',e=>{if(!touch)return;const {ring,x}=touch,dx=e.clientX-x;document.querySelector(`.ring-group[data-ring="${ring}"]`).classList.remove('active');touch=null;const rect=$('#board').getBoundingClientRect(),dir=Math.abs(dx)>24?(dx>0?1:-1):(e.clientX<rect.left+rect.width/2?-1:1);rotate(ring,dir)});hit.addEventListener('pointercancel',()=>{document.querySelectorAll('.ring-group').forEach(g=>g.classList.remove('active'));touch=null})});document.querySelectorAll('.gate-button').forEach(g=>{g.addEventListener('pointerdown',e=>e.stopPropagation());g.addEventListener('click',e=>{e.stopPropagation();swap(+g.dataset.gate)});g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();swap(+g.dataset.gate)}})})}
  function sound(freq,duration){if(!progress.settings.sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch(_){}}
  function renderLevelGrid(which=selectMode){selectMode=which;$('#classicTab').classList.toggle('active',which==='classic');$('#gateTab').classList.toggle('active',which==='gate');const grid=$('#levelGrid'),data=which==='gate'?progress.gate:progress,list=which==='gate'?COLOR_ORBIT_GATE_LEVELS:COLOR_ORBIT_LEVELS;grid.textContent='';list.forEach(l=>{const b=document.createElement('button'),open=l.id<=data.unlocked;b.className='level-card'+(open?'':' locked');b.disabled=!open;b.innerHTML=`${which==='gate'?'G':''}${l.id}<small>${'★'.repeat(data.stars[l.id]||0)}</small>`;b.onclick=()=>loadLevel(l.id,which);grid.append(b)})}
  function levelSelect(){renderLevelGrid();show('level')}
  $('#undoButton').onclick=undo;$('#resetButton').onclick=reset;$('#levelsButton').onclick=levelSelect;$('#classicTab').onclick=()=>renderLevelGrid('classic');$('#gateTab').onclick=()=>renderLevelGrid('gate');$('#settingsButton').onclick=()=>{show('settings');$('#soundToggle').checked=progress.settings.sound;$('#colorHelpToggle').checked=progress.settings.colorHelp};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>show('game'));$('#soundToggle').onchange=e=>{progress.settings.sound=e.target.checked;OrbitStorage.save(progress)};$('#colorHelpToggle').onchange=e=>{progress.settings.colorHelp=e.target.checked;OrbitStorage.save(progress);buildBoard()};$('#nextButton').onclick=()=>loadLevel(level.id+1,mode);$('#retryButton').onclick=()=>loadLevel(level.id,mode);$('#selectButton').onclick=levelSelect;
  loadLevel(Math.min(progress.unlocked,20),'classic');
})();
