(function(){'use strict';
  const NS='http://www.w3.org/2000/svg',palette={R:'#ff5d73',B:'#4dabf7',Y:'#ffd166',G:'#50d890'},classicColors=Object.values(palette).concat('#b784f7'),symbols={R:'●',B:'▲',Y:'■',G:'◆'};
  const $=s=>document.querySelector(s),svg=(tag,attrs={})=>{const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e};
  let progress=OrbitStorage.load(),mode='classic',level,state,initial,history=[],moves=0,busy=false,cleared=false,renderAngles=[],audio,selectMode='classic',tutorialStep=0;
  const copy=s=>mode==='gate'?s.map(r=>r.slice()):s.slice();
  function show(name){['game','level','settings'].forEach(n=>$(`#${n}Screen`).classList.toggle('hidden',n!==name));$('#clearDialog').classList.add('hidden')}
  function loadLevel(id,nextMode=mode){mode=nextMode;level=(mode==='gate'?COLOR_ORBIT_GATE_LEVELS:COLOR_ORBIT_LEVELS)[id-1];initial=mode==='gate'?level.rings.map(r=>r.slice()):level.initial.slice();state=copy(initial);renderAngles=mode==='gate'?[0,0,0]:state.map(v=>v*360/level.slots);history=[];moves=0;busy=false;cleared=false;tutorialStep=mode==='gate'&&id===1&&!progress.gate.tutorialCompleted?1:0;show('game');buildBoard();updateUI()}
  function polar(r,a,cx=180){const q=(a-90)*Math.PI/180;return[cx+r*Math.cos(q),180+r*Math.sin(q)]}
  function tile(group,x,y,color,key,r=13){const g=svg('g');g.append(svg('circle',{cx:x,cy:y,r,fill:color,class:'tile tile-halo'}));if(progress.settings.colorHelp){const t=svg('text',{x,y:y+1,class:'tile-symbol'});t.textContent=key?symbols[key]:'';g.append(t)}group.append(g)}
  function buildBoard(){const board=$('#board');board.textContent='';if(mode==='gate')buildGateBoard(board);else buildClassicBoard(board);bindBoard()}
  function buildClassicBoard(board){const gap=level.rings===5?27:32,outer=154,radii=Array.from({length:level.rings},(_,i)=>outer-i*gap);radii.forEach((r,i)=>{board.append(svg('circle',{cx:180,cy:180,r,class:'ring-track','stroke-width':gap-7}));const group=svg('g',{class:'ring-group','data-ring':i});for(let s=0;s<level.slots;s++){const [x,y]=polar(r,s*360/level.slots);tile(group,x,y,classicColors[s])}board.append(group);board.append(svg('circle',{cx:180,cy:180,r,'stroke-width':gap,class:'ring-hit','data-hit':i}));const effects=level.effects[i].map((v,j)=>v&&j!==i?`${j+1}${v>0?'↻':'↺'}`:'').filter(Boolean);if(effects.length){const [x,y]=polar(r,90),m=svg('text',{x,y:y+3,class:'link-mark'});m.textContent=effects.join(' ');board.append(m)}});addCore(board);render()}
  function buildGateBoard(board){const cx=158,radii=[146,104,62],rightXs=radii.map(r=>cx+r);[0,90,180,270].forEach(a=>{const [x,y]=polar(158,a,cx);board.append(svg('line',{x1:cx,y1:180,x2:x,y2:y,class:'goal-line'}))});[[0,1],[1,2]].forEach(pair=>board.append(svg('line',{x1:rightXs[pair[0]],y1:180,x2:rightXs[pair[1]],y2:180,class:'gate-guide-line'})));radii.forEach((r,i)=>{board.append(svg('circle',{cx,cy:180,r,class:'ring-track','stroke-width':28}));const group=svg('g',{class:'ring-group gate-ring-group','data-ring':i});state[i].forEach((key,s)=>{const [x,y]=polar(r,s*90,cx);const spot=svg('g',{'data-tile':`${i}-${s}`});if(s===1)spot.classList.add('gate-candidate');tile(spot,x,y,palette[key],key,15);group.append(spot)});board.append(group);board.append(svg('circle',{cx,cy:180,r,'stroke-width':31,class:'ring-hit','data-hit':i}))});addCore(board,cx);[0,1].forEach(gate=>{const x=gate===0?342:300,button=svg('g',{class:'gate-button','data-gate':gate,role:'button','aria-label':`GATE ${gate?'B':'A'}: 右側の${gate?'中央と内':'外と中'}リングの色を交換`,tabindex:0});button.append(svg('circle',{cx:x,cy:180,r:22,class:'gate-touch'}));button.append(svg('circle',{cx:x,cy:180,r:16,class:'gate-hit'}));const t=svg('text',{x,y:184,class:'gate-label'});t.textContent='⇄';button.append(t);board.append(button)});const hint=svg('text',{x:cx,y:20,class:'rotation-hint'});hint.textContent='↺       ↻';board.append(hint);applyTutorialVisuals()}
  function highlightGate(gate,on=true){[gate,gate+1].forEach(r=>document.querySelector(`[data-tile="${r}-1"]`)?.classList.toggle('gate-target',on))}
  function applyTutorialVisuals(){if(!tutorialStep)return;if(tutorialStep===1){document.querySelector('[data-gate="0"]')?.classList.add('tutorial-target');highlightGate(0);const t=svg('text',{x:284,y:154,class:'swap-demo'});t.textContent='⇄';$('#board').append(t)}else{document.querySelector('[data-ring="0"]')?.classList.add('tutorial-ring');const t=svg('text',{x:180,y:45,class:'swipe-demo'});t.textContent='☝  ⟶';$('#board').append(t)}}
  function addCore(board,cx=180){board.append(svg('circle',{cx,cy:180,r:mode==='gate'?27:level.rings===5?27:38,class:'center-core'}));const t=svg('text',{x:cx,y:183,class:'center-label'});t.textContent=mode==='gate'?'GATE':'ORBIT';board.append(t)}
  function render(){document.querySelectorAll('.ring-group').forEach((g,i)=>g.style.transform=`rotate(${renderAngles[i]}deg)`)}
  function updateUI(){const data=mode==='gate'?progress.gate:progress;$('#levelLabel').textContent=mode==='gate'?`GATE TEST ${level.id}`:`LEVEL ${level.id}`;$('#moveCount').textContent=moves;$('#bestMoves').textContent=data.bestMoves[level.id]??'—';$('#levelHint').textContent=mode==='gate'?'同じ方向の3色をそろえよう':level.hint;$('#undoButton').disabled=!history.length||busy||!!tutorialStep;$('#resetButton').disabled=busy;const guide=$('#gateGuide'),how=$('#howToButton');guide.classList.toggle('hidden',!tutorialStep);how.classList.toggle('hidden',mode!=='gate'||level.id!==1||!!tutorialStep);if(tutorialStep){$('#guideText').textContent=tutorialStep===1?'① 光っている2色をGATEで交換しよう':tutorialStep===2?'② 外側リングを右へスワイプ':'③ もう一度、外側リングを右へ';$('#guideSub').textContent=tutorialStep===1?'⇄ が交換する2つの色を光らせています':'右半分をタップしても回せます'}}
  function remember(){history.push({state:copy(state),angles:renderAngles.slice()});moves++}
  function rotate(source,direction){if(busy||cleared||tutorialStep===1||(tutorialStep>1&&(source!==0||direction!==1)))return;busy=true;remember();if(mode==='gate'){state=OrbitSolver.applyGate(state,{type:'rotate',ring:source,direction});renderAngles[source]+=direction*90;if(tutorialStep===2)tutorialStep=3;else if(tutorialStep===3)tutorialStep=0}else{state=OrbitSolver.apply(state,level.effects,source,direction,level.slots);level.effects[source].forEach((effect,i)=>renderAngles[i]+=effect*direction*360/level.slots)}render();sound(220,.045);updateUI();setTimeout(()=>{busy=false;if(mode==='gate'){renderAngles=[0,0,0];buildBoard()}updateUI();checkClear()},250)}
  function swap(gate){if(mode!=='gate'||busy||cleared||(tutorialStep&&!(tutorialStep===1&&gate===0)))return;remember();state=OrbitSolver.applyGate(state,{type:'swap',gate});if(tutorialStep===1)tutorialStep=2;buildBoard();const button=document.querySelector(`[data-gate="${gate}"]`);button.classList.add('swapped');busy=true;sound(330,.06);updateUI();setTimeout(()=>{busy=false;button.classList.remove('swapped');updateUI();checkClear()},240)}
  function undo(){if(busy||tutorialStep||!history.length||cleared)return;const prev=history.pop();state=prev.state;renderAngles=prev.angles;moves=Math.max(0,moves-1);buildBoard();sound(160,.04);updateUI()}
  function reset(){if(busy)return;state=copy(initial);renderAngles=mode==='gate'?[0,0,0]:state.map(v=>v*360/level.slots);history=[];moves=0;cleared=false;if(mode==='gate'&&level.id===1&&tutorialStep)tutorialStep=1;buildBoard();updateUI()}
  function checkClear(){if(mode==='gate'?OrbitSolver.gateSolved(state):OrbitSolver.solved(state))finish()}
  function finish(){cleared=true;const optimum=(mode==='gate'?OrbitSolver.solveGate(level):OrbitSolver.solve(level)).moves,stars=moves<=optimum+1?3:moves<=optimum+4?2:1;if(mode==='gate'){if(level.id===1)progress.gate.tutorialCompleted=true;OrbitStorage.recordGateClear(progress,level.id,moves,stars)}else OrbitStorage.recordClear(progress,level.id,moves,stars);$('#clearPulse').classList.add('show');sound(440,.1);setTimeout(()=>sound(660,.16),100);setTimeout(()=>{$('#clearPulse').classList.remove('show');$('#stars').textContent='★'.repeat(stars)+'☆'.repeat(3-stars);$('#clearStats').textContent=`${moves} MOVES · OPTIMUM ${optimum}`;$('#nextButton').classList.toggle('hidden',level.id===(mode==='gate'?5:20));$('#clearDialog').classList.remove('hidden')},650)}
  function bindBoard(){let touch=null;document.querySelectorAll('.ring-hit').forEach(hit=>{hit.addEventListener('pointerdown',e=>{if(busy)return;const ring=+hit.dataset.hit;touch={ring,x:e.clientX};hit.setPointerCapture(e.pointerId);document.querySelector(`.ring-group[data-ring="${ring}"]`).classList.add('active')});hit.addEventListener('pointerup',e=>{if(!touch)return;const {ring,x}=touch,dx=e.clientX-x;document.querySelector(`.ring-group[data-ring="${ring}"]`).classList.remove('active');touch=null;const rect=$('#board').getBoundingClientRect(),dir=Math.abs(dx)>24?(dx>0?1:-1):(e.clientX<rect.left+rect.width/2?-1:1);rotate(ring,dir)});hit.addEventListener('pointercancel',()=>{document.querySelectorAll('.ring-group').forEach(g=>g.classList.remove('active'));touch=null})});document.querySelectorAll('.gate-button').forEach(g=>{const n=+g.dataset.gate;g.addEventListener('pointerdown',e=>{e.stopPropagation();highlightGate(n)});g.addEventListener('pointerleave',()=>{if(!(tutorialStep===1&&n===0))highlightGate(n,false)});g.addEventListener('focus',()=>highlightGate(n));g.addEventListener('blur',()=>{if(!(tutorialStep===1&&n===0))highlightGate(n,false)});g.addEventListener('click',e=>{e.stopPropagation();swap(n)});g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();swap(n)}})})}
  function sound(freq,duration){if(!progress.settings.sound)return;try{audio=audio||new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=freq;o.type='sine';g.gain.setValueAtTime(.045,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}catch(_){}}
  function renderLevelGrid(which=selectMode){selectMode=which;$('#classicTab').classList.toggle('active',which==='classic');$('#gateTab').classList.toggle('active',which==='gate');const grid=$('#levelGrid'),data=which==='gate'?progress.gate:progress,list=which==='gate'?COLOR_ORBIT_GATE_LEVELS:COLOR_ORBIT_LEVELS;grid.textContent='';list.forEach(l=>{const b=document.createElement('button'),open=l.id<=data.unlocked;b.className='level-card'+(open?'':' locked');b.disabled=!open;b.innerHTML=`${which==='gate'?'G':''}${l.id}<small>${'★'.repeat(data.stars[l.id]||0)}</small>`;b.onclick=()=>loadLevel(l.id,which);grid.append(b)})}
  function levelSelect(){renderLevelGrid();show('level')}
  $('#undoButton').onclick=undo;$('#resetButton').onclick=reset;$('#levelsButton').onclick=levelSelect;$('#classicTab').onclick=()=>renderLevelGrid('classic');$('#gateTab').onclick=()=>renderLevelGrid('gate');$('#settingsButton').onclick=()=>{show('settings');$('#soundToggle').checked=progress.settings.sound;$('#colorHelpToggle').checked=progress.settings.colorHelp};document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>show('game'));$('#soundToggle').onchange=e=>{progress.settings.sound=e.target.checked;OrbitStorage.save(progress)};$('#colorHelpToggle').onchange=e=>{progress.settings.colorHelp=e.target.checked;OrbitStorage.save(progress);buildBoard()};$('#nextButton').onclick=()=>loadLevel(level.id+1,mode);$('#retryButton').onclick=()=>loadLevel(level.id,mode);$('#selectButton').onclick=levelSelect;
  $('#howToButton').onclick=()=>{reset();tutorialStep=1;buildBoard();updateUI()};
  loadLevel(Math.min(progress.unlocked,20),'classic');
})();
