'use strict';
const assert=require('assert'),levels=require('./levels.js'),solver=require('./solver.js');
assert.equal(levels.length,20);
for(const level of levels){const result=solver.solve(level);assert(result,`Level ${level.id} is unsolvable`);let state=level.initial.slice();for(const move of result.path)state=solver.apply(state,level.effects,move.ring,move.direction,level.slots);assert(solver.solved(state));for(let r=0;r<level.rings;r++){const cw=solver.apply(level.initial,level.effects,r,1,level.slots),back=solver.apply(cw,level.effects,r,-1,level.slots);assert.deepEqual(back,level.initial,`Level ${level.id} direction inverse failed`)}}
const sample=levels[16],after=solver.apply(sample.initial,sample.effects,1,1,sample.slots),undo=sample.initial.slice();assert.notDeepEqual(after,undo);assert.deepEqual(undo,sample.initial);assert(solver.solved([2,2,2]));assert(!solver.solved([2,2,1]));
assert.equal(levels.gate.length,5);
const expected=[3,4,6,8,10];
levels.gate.forEach((level,i)=>{const result=solver.solveGate(level);assert(result,`Gate ${level.id} is unsolvable`);assert.equal(result.moves,expected[i]);assert(result.path.some(m=>m.type==='swap'),`Gate ${level.id} needs no swap`);assert.equal(solver.solveGate(level,level.rings,{allowSwaps:false}),null,`Gate ${level.id} can be rotation-solved`);if(i>=2)assert.equal(new Set(result.path.filter(m=>m.type==='swap').map(m=>m.gate)).size,2);let state=level.rings.map(r=>r.slice());for(const move of result.path)state=solver.applyGate(state,move);assert(solver.gateSolved(state))});
const gateSample=levels.gate[0].rings,clockwise=solver.applyGate(gateSample,{type:'rotate',ring:0,direction:1});assert.deepEqual(clockwise[0],[gateSample[0][3],...gateSample[0].slice(0,3)]);assert.deepEqual(solver.applyGate(clockwise,{type:'rotate',ring:0,direction:-1}),gateSample);const swapped=solver.applyGate(gateSample,{type:'swap',gate:0});assert.equal(swapped[0][1],gateSample[1][1]);assert.equal(swapped[1][1],gateSample[0][1]);assert.deepEqual(solver.applyGate(swapped,{type:'swap',gate:0}),gateSample);
const memory={};global.localStorage={getItem:k=>memory[k]??null,setItem:(k,v)=>memory[k]=v};const storage=require('./storage.js'),progress=storage.load();progress.settings.colorHelp=true;storage.recordClear(progress,1,4,3);const restored=storage.load();assert.equal(restored.unlocked,2);assert.equal(restored.stars[1],3);assert.equal(restored.bestMoves[1],4);assert.equal(restored.settings.colorHelp,true);
storage.recordGateClear(restored,1,3,3);const gateRestored=storage.load();assert.equal(gateRestored.gate.unlocked,2);assert.equal(gateRestored.gate.bestMoves[1],3);assert.equal(gateRestored.unlocked,2);
assert.equal(gateRestored.gate.tutorialCompleted,false);gateRestored.gate.tutorialCompleted=true;storage.save(gateRestored);assert.equal(storage.load().gate.tutorialCompleted,true);
console.log(`Validated ${levels.length} solvable levels; max optimum ${Math.max(...levels.map(l=>solver.solve(l).moves))} moves.`);
